// Code generated by bencgen golang. DO NOT EDIT.
// source: ../schemas/Certificate.benc

package cert

import (
    "github.com/deneonet/benc/std"
    "github.com/deneonet/benc/impl/gen"
)

// Struct - Certificate
type Certificate struct {
    PrivateKey []byte
    PublicKey []byte
    PublicKeySignature []byte
    Version int
    CreatedAt int64
}

// Reserved Ids - Certificate
var certificateRIds = []uint16{}

// Size - Certificate
func (certificate *Certificate) Size() int {
    return certificate.size(0)
}

// Nested Size - Certificate
func (certificate *Certificate) size(id uint16) (s int) {
    s += bstd.SizeBytes(certificate.PrivateKey) + 2
    s += bstd.SizeBytes(certificate.PublicKey) + 2
    s += bstd.SizeBytes(certificate.PublicKeySignature) + 2
    s += bstd.SizeInt(certificate.Version) + 2
    s += bstd.SizeInt64() + 2

    if id > 255 {
        s += 5
        return
    }
    s += 4
    return
}

// SizePlain - Certificate
func (certificate *Certificate) SizePlain() (s int) {
    s += bstd.SizeBytes(certificate.PrivateKey)
    s += bstd.SizeBytes(certificate.PublicKey)
    s += bstd.SizeBytes(certificate.PublicKeySignature)
    s += bstd.SizeInt(certificate.Version)
    s += bstd.SizeInt64()
    return
}

// Marshal - Certificate
func (certificate *Certificate) Marshal(b []byte) {
    certificate.marshal(0, b, 0)
}

// Nested Marshal - Certificate
func (certificate *Certificate) marshal(tn int, b []byte, id uint16) (n int) {
    n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 1)
    n = bstd.MarshalBytes(n, b, certificate.PrivateKey)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 2)
    n = bstd.MarshalBytes(n, b, certificate.PublicKey)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 3)
    n = bstd.MarshalBytes(n, b, certificate.PublicKeySignature)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Varint, 4)
    n = bstd.MarshalInt(n, b, certificate.Version)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed64, 5)
    n = bstd.MarshalInt64(n, b, certificate.CreatedAt)

    n += 2
    b[n-2] = 1
    b[n-1] = 1
    return
}

// MarshalPlain - Certificate
func (certificate *Certificate) MarshalPlain(tn int, b []byte) (n int) {
    n = tn
    n = bstd.MarshalBytes(n, b, certificate.PrivateKey)
    n = bstd.MarshalBytes(n, b, certificate.PublicKey)
    n = bstd.MarshalBytes(n, b, certificate.PublicKeySignature)
    n = bstd.MarshalInt(n, b, certificate.Version)
    n = bstd.MarshalInt64(n, b, certificate.CreatedAt)
    return n
}

// Unmarshal - Certificate
func (certificate *Certificate) Unmarshal(b []byte) (err error) {
    _, err = certificate.unmarshal(0, b, []uint16{}, 0)
    return
}

// Nested Unmarshal - Certificate
func (certificate *Certificate) unmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
    var ok bool
    if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, certificateRIds, 1); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, certificate.PrivateKey, err = bstd.UnmarshalBytes(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, certificateRIds, 2); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, certificate.PublicKey, err = bstd.UnmarshalBytes(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, certificateRIds, 3); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, certificate.PublicKeySignature, err = bstd.UnmarshalBytes(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, certificateRIds, 4); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, certificate.Version, err = bstd.UnmarshalInt(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, certificateRIds, 5); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, certificate.CreatedAt, err = bstd.UnmarshalInt64(n, b); err != nil {
            return
        }
    }
    n += 2
    return
}

// UnmarshalPlain - Certificate
func (certificate *Certificate) UnmarshalPlain(tn int, b []byte) (n int, err error) {
    n = tn
    if n, certificate.PrivateKey, err = bstd.UnmarshalBytes(n, b); err != nil {
        return
    }
    if n, certificate.PublicKey, err = bstd.UnmarshalBytes(n, b); err != nil {
        return
    }
    if n, certificate.PublicKeySignature, err = bstd.UnmarshalBytes(n, b); err != nil {
        return
    }
    if n, certificate.Version, err = bstd.UnmarshalInt(n, b); err != nil {
        return
    }
    if n, certificate.CreatedAt, err = bstd.UnmarshalInt64(n, b); err != nil {
        return
    }
    return
}

