// Code generated by bencgen golang. DO NOT EDIT.
// source: ../schemas/RootKey.benc

package cert

import (
    "github.com/deneonet/benc/std"
    "github.com/deneonet/benc/impl/gen"
)

// Struct - RootKey
type RootKey struct {
    PublicKey []byte
    Version int
    CreatedAt int64
}

// Reserved Ids - RootKey
var rootKeyRIds = []uint16{}

// Size - RootKey
func (rootKey *RootKey) Size() int {
    return rootKey.size(0)
}

// Nested Size - RootKey
func (rootKey *RootKey) size(id uint16) (s int) {
    s += bstd.SizeBytes(rootKey.PublicKey) + 2
    s += bstd.SizeInt(rootKey.Version) + 2
    s += bstd.SizeInt64() + 2

    if id > 255 {
        s += 5
        return
    }
    s += 4
    return
}

// SizePlain - RootKey
func (rootKey *RootKey) SizePlain() (s int) {
    s += bstd.SizeBytes(rootKey.PublicKey)
    s += bstd.SizeInt(rootKey.Version)
    s += bstd.SizeInt64()
    return
}

// Marshal - RootKey
func (rootKey *RootKey) Marshal(b []byte) {
    rootKey.marshal(0, b, 0)
}

// Nested Marshal - RootKey
func (rootKey *RootKey) marshal(tn int, b []byte, id uint16) (n int) {
    n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 1)
    n = bstd.MarshalBytes(n, b, rootKey.PublicKey)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Varint, 2)
    n = bstd.MarshalInt(n, b, rootKey.Version)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed64, 3)
    n = bstd.MarshalInt64(n, b, rootKey.CreatedAt)

    n += 2
    b[n-2] = 1
    b[n-1] = 1
    return
}

// MarshalPlain - RootKey
func (rootKey *RootKey) MarshalPlain(tn int, b []byte) (n int) {
    n = tn
    n = bstd.MarshalBytes(n, b, rootKey.PublicKey)
    n = bstd.MarshalInt(n, b, rootKey.Version)
    n = bstd.MarshalInt64(n, b, rootKey.CreatedAt)
    return n
}

// Unmarshal - RootKey
func (rootKey *RootKey) Unmarshal(b []byte) (err error) {
    _, err = rootKey.unmarshal(0, b, []uint16{}, 0)
    return
}

// Nested Unmarshal - RootKey
func (rootKey *RootKey) unmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
    var ok bool
    if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, rootKeyRIds, 1); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, rootKey.PublicKey, err = bstd.UnmarshalBytes(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, rootKeyRIds, 2); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, rootKey.Version, err = bstd.UnmarshalInt(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, rootKeyRIds, 3); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, rootKey.CreatedAt, err = bstd.UnmarshalInt64(n, b); err != nil {
            return
        }
    }
    n += 2
    return
}

// UnmarshalPlain - RootKey
func (rootKey *RootKey) UnmarshalPlain(tn int, b []byte) (n int, err error) {
    n = tn
    if n, rootKey.PublicKey, err = bstd.UnmarshalBytes(n, b); err != nil {
        return
    }
    if n, rootKey.Version, err = bstd.UnmarshalInt(n, b); err != nil {
        return
    }
    if n, rootKey.CreatedAt, err = bstd.UnmarshalInt64(n, b); err != nil {
        return
    }
    return
}

