// Code generated by bencgen go. DO NOT EDIT.
// source: client_root_key.benc

package cert

import (
    "github.com/deneonet/benc/std"
    "github.com/deneonet/benc/impl/gen"


)

// Struct - ClientRootKey
type ClientRootKey struct {
    Key []byte
    Version int
    CreatedAt int64
}

// Reserved Ids - ClientRootKey
var clientRootKeyRIds = []uint16{}

// Size - ClientRootKey
func (clientRootKey *ClientRootKey) Size() int {
    return clientRootKey.NestedSize(0)
}

// Nested Size - ClientRootKey
func (clientRootKey *ClientRootKey) NestedSize(id uint16) (s int) {
    s += bstd.SizeBytes(clientRootKey.Key) + 2
    s += bstd.SizeInt(clientRootKey.Version) + 2
    s += bstd.SizeInt64() + 2

    if id > 255 {
        s += 5
        return
    }
    s += 4
    return
}

// SizePlain - ClientRootKey
func (clientRootKey *ClientRootKey) SizePlain() (s int) {
    s += bstd.SizeBytes(clientRootKey.Key)
    s += bstd.SizeInt(clientRootKey.Version)
    s += bstd.SizeInt64()
    return
}

// Marshal - ClientRootKey
func (clientRootKey *ClientRootKey) Marshal(b []byte) {
    clientRootKey.NestedMarshal(0, b, 0)
}

// Nested Marshal - ClientRootKey
func (clientRootKey *ClientRootKey) NestedMarshal(tn int, b []byte, id uint16) (n int) {
    n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 1)
    n = bstd.MarshalBytes(n, b, clientRootKey.Key)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Varint, 2)
    n = bstd.MarshalInt(n, b, clientRootKey.Version)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Fixed64, 3)
    n = bstd.MarshalInt64(n, b, clientRootKey.CreatedAt)

    n += 2
    b[n-2] = 1
    b[n-1] = 1
    return
}

// MarshalPlain - ClientRootKey
func (clientRootKey *ClientRootKey) MarshalPlain(tn int, b []byte) (n int) {
    n = tn
    n = bstd.MarshalBytes(n, b, clientRootKey.Key)
    n = bstd.MarshalInt(n, b, clientRootKey.Version)
    n = bstd.MarshalInt64(n, b, clientRootKey.CreatedAt)
    return n
}

// Unmarshal - ClientRootKey
func (clientRootKey *ClientRootKey) Unmarshal(b []byte) (err error) {
    _, err = clientRootKey.NestedUnmarshal(0, b, []uint16{}, 0)
    return
}

// Nested Unmarshal - ClientRootKey
func (clientRootKey *ClientRootKey) NestedUnmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
    var ok bool
    if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, clientRootKeyRIds, 1); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, clientRootKey.Key, err = bstd.UnmarshalBytes(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, clientRootKeyRIds, 2); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, clientRootKey.Version, err = bstd.UnmarshalInt(n, b); err != nil {
            return
        }
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, clientRootKeyRIds, 3); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, clientRootKey.CreatedAt, err = bstd.UnmarshalInt64(n, b); err != nil {
            return
        }
    }
    n += 2
    return
}

// UnmarshalPlain - ClientRootKey
func (clientRootKey *ClientRootKey) UnmarshalPlain(tn int, b []byte) (n int, err error) {
    n = tn
    if n, clientRootKey.Key, err = bstd.UnmarshalBytes(n, b); err != nil {
        return
    }
    if n, clientRootKey.Version, err = bstd.UnmarshalInt(n, b); err != nil {
        return
    }
    if n, clientRootKey.CreatedAt, err = bstd.UnmarshalInt64(n, b); err != nil {
        return
    }
    return
}

