// Code generated by bencgen golang. DO NOT EDIT.
// source: .\message\packet.benc

package message

import (
    "github.com/deneonet/benc/std"
    "github.com/deneonet/benc/impl/gen"
)

// Struct - Packet
type Packet struct {
    Data string
}

// Reserved Ids - Packet
var packetRIds = []uint16{}

// Size - Packet
func (packet *Packet) Size() int {
    return packet.size(0)
}

// Nested Size - Packet
func (packet *Packet) size(id uint16) (s int) {
    s += bstd.SizeString(packet.Data) + 2

    if id > 255 {
        s += 5
        return
    }
    s += 4
    return
}

// SizePlain - Packet
func (packet *Packet) SizePlain() (s int) {
    s += bstd.SizeString(packet.Data)
    return
}

// Marshal - Packet
func (packet *Packet) Marshal(b []byte) {
    packet.marshal(0, b, 0)
}

// Nested Marshal - Packet
func (packet *Packet) marshal(tn int, b []byte, id uint16) (n int) {
    n = bgenimpl.MarshalTag(tn, b, bgenimpl.Container, id)
    n = bgenimpl.MarshalTag(n, b, bgenimpl.Bytes, 1)
    n = bstd.MarshalString(n, b, packet.Data)

    n += 2
    b[n-2] = 1
    b[n-1] = 1
    return
}

// MarshalPlain - Packet
func (packet *Packet) MarshalPlain(tn int, b []byte) (n int) {
    n = tn
    n = bstd.MarshalString(n, b, packet.Data)
    return n
}

// Unmarshal - Packet
func (packet *Packet) Unmarshal(b []byte) (err error) {
    _, err = packet.unmarshal(0, b, []uint16{}, 0)
    return
}

// Nested Unmarshal - Packet
func (packet *Packet) unmarshal(tn int, b []byte, r []uint16, id uint16) (n int, err error) {
    var ok bool
    if n, ok, err = bgenimpl.HandleCompatibility(tn, b, r, id); !ok {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if n, ok, err = bgenimpl.HandleCompatibility(n, b, packetRIds, 1); err != nil {
        if err == bgenimpl.ErrEof {
            return n, nil
        }
        return
    }
    if ok {
        if n, packet.Data, err = bstd.UnmarshalString(n, b); err != nil {
            return
        }
    }
    n += 2
    return
}

// UnmarshalPlain - Packet
func (packet *Packet) UnmarshalPlain(tn int, b []byte) (n int, err error) {
    n = tn
    if n, packet.Data, err = bstd.UnmarshalString(n, b); err != nil {
        return
    }
    return
}

